
IF OBJECT_ID('dbo.DIM_GRUPO_EDAD', 'U') IS NULL
BEGIN
	CREATE TABLE dbo.DIM_GRUPO_EDAD (
		IdGrupoEdad tinyint IDENTITY(1,1) NOT NULL,
		NomGrupoEdad nvarchar(20) NOT NULL,
		CONSTRAINT DIM_GRUPO_EDAD_PK PRIMARY KEY (IdGrupoEdad)
	);
END;