-- Datawarehousecolext.dbo.FAC_COLOMBIANOSENELEXTERIOR definition

-- Drop table

-- DROP TABLE Datawarehousecolext.dbo.FAC_COLOMBIANOSENELEXTERIOR;

CREATE TABLE Datawarehousecolext.dbo.FAC_COLOMBIANOSENELEXTERIOR (
	IdCodigopais int NOT NULL,
	CodISOpais varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	IdGenero tinyint NOT NULL,
	IdEstadoCivil tinyint NOT NULL,
	IdEtnia tinyint NOT NULL,
	IdGrupoEdad tinyint NOT NULL,
	CONSTRAINT FAC_COLOMBIANOSENELEXTERIOR_DIM_Georefenciacion_Paises_PK PRIMARY KEY (IdCodigopais),
	CONSTRAINT FAC_COLOMBIANOSENELEXTERIOR_DIM_ESTADO_CIVIL_FK FOREIGN KEY (IdEstadoCivil) REFERENCES Datawarehousecolext.dbo.DIM_ESTADO_CIVIL(IdEstadoCivil),
	CONSTRAINT FAC_COLOMBIANOSENELEXTERIOR_DIM_ETNIA_FK FOREIGN KEY (IdEtnia) REFERENCES Datawarehousecolext.dbo.DIM_ETNIA(IdEtnia),
	CONSTRAINT FAC_COLOMBIANOSENELEXTERIOR_DIM_GENERO_FK FOREIGN KEY (IdGenero) REFERENCES Datawarehousecolext.dbo.DIM_GENERO(IdGenero),
	CONSTRAINT FAC_COLOMBIANOSENELEXTERIOR_DIM_GRUPO_EDAD_FK FOREIGN KEY (IdGrupoEdad) REFERENCES Datawarehousecolext.dbo.DIM_GRUPO_EDAD(IdGrupoEdad)
);